# Generated by Django 6.0.4 on 2026-04-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover_url',
        ),
        migrations.RemoveField(
            model_name='song',
            name='cover_url',
        ),
        migrations.RemoveField(
            model_name='song',
            name='file_url',
        ),
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='album_covers/'),
        ),
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='song',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='song_covers/'),
        ),
    ]
