# Generated by Django 6.0.4 on 2026-04-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_album_cover_url_remove_song_cover_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
