# Generated by Django 6.0.4 on 2026-04-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_album_cover_alter_song_cover'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Tag',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(related_name='albums', to='music.tag'),
        ),
        migrations.AddField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(related_name='songs', to='music.tag'),
        ),
    ]
