# Generated by Django 6.0.4 on 2026-04-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_rename_genre_tag_remove_song_genre_album_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Hip-Hop', 'Hip-Hop'), ('Rap', 'Rap'), ('R&B', 'R&B'), ('Reggaeton', 'Reggaeton'), ('K-Pop', 'K-Pop'), ('Electronic', 'Electronic'), ('EDM', 'EDM'), ('Jazz', 'Jazz'), ('Blues', 'Blues'), ('Country', 'Country'), ('Folk', 'Folk'), ('Música Clásica', 'Música Clásica'), ('Soul', 'Soul'), ('Funk', 'Funk'), ('Salsa', 'Salsa'), ('Bachata', 'Bachata'), ('Cumbia', 'Cumbia'), ('Bossa Nova', 'Bossa Nova'), ('Merengue', 'Merengue'), ('Tango', 'Tango'), ('Heavy Metal', 'Heavy Metal'), ('Punk', 'Punk'), ('Ska', 'Ska'), ('Reggae', 'Reggae'), ('Synthwave', 'Synthwave'), ('Lo-fi', 'Lo-fi'), ('Trap', 'Trap'), ('Afrobeats', 'Afrobeats'), ('Hyperpop', 'Hyperpop')], max_length=50, unique=True),
        ),
    ]
