# Generated by Django 6.0.4 on 2026-05-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_album_options_alter_song_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={},
        ),
        migrations.RemoveField(
            model_name='album',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='album',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='song',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='song',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='song',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(related_name='albums', to='music.tag'),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(related_name='songs', to='music.tag'),
        ),
    ]
