# Generated by Django 6.0.4 on 2026-05-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_album_options_alter_song_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='explicit',
        ),
    ]
