# Generated by Django 6.0.4 on 2026-05-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_listeninghistory_usertag'),
        ('music', '0008_remove_song_explicit'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborations', to='accounts.artistprofile'),
        ),
        migrations.AlterField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='albums', to='music.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Hip-Hop', 'Hip-Hop'), ('Rap', 'Rap'), ('R&B', 'R&B'), ('Reggaeton', 'Reggaeton'), ('K-Pop', 'K-Pop'), ('Electronic', 'Electronic'), ('EDM', 'EDM'), ('Jazz', 'Jazz'), ('Blues', 'Blues'), ('Country', 'Country'), ('Folk', 'Folk'), ('Música Clásica', 'Música Clásica'), ('Soul', 'Soul'), ('Funk', 'Funk'), ('Salsa', 'Salsa'), ('Bachata', 'Bachata'), ('Cumbia', 'Cumbia'), ('Bossa Nova', 'Bossa Nova'), ('Merengue', 'Merengue'), ('Tango', 'Tango'), ('Heavy Metal', 'Heavy Metal'), ('Punk', 'Punk'), ('Ska', 'Ska'), ('Reggae', 'Reggae'), ('Synthwave', 'Synthwave'), ('Lo-fi', 'Lo-fi'), ('Trap', 'Trap'), ('Afrobeats', 'Afrobeats'), ('Hyperpop', 'Hyperpop'), ('Nulo', 'Nulo')], max_length=50, unique=True),
        ),
    ]
