# Generated by Django 6.0.4 on 2026-05-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_song_collaborators_alter_album_tags_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_explicit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='is_explicit',
            field=models.BooleanField(default=False),
        ),
    ]
