# Generated by Django 6.0.4 on 2026-05-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_album_is_explicit_song_is_explicit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='covers/'),
        ),
    ]
