# Generated by Django 6.0.4 on 2026-05-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
