# Generated by Django 6.0.4 on 2026-05-06 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_playlist_cover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_playlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
