# Generated by Django 6.0.4 on 2026-05-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_playlist_saved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_liked_playlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playlist',
            name='order_by_field',
            field=models.CharField(choices=[('added', 'Añadida'), ('name', 'Nombre')], default='added', max_length=20),
        ),
    ]
