# Generated by Django 6.0.4 on 2026-05-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_playlist_is_liked_playlist_playlist_order_by_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='liked_playlist_cover',
            field=models.ImageField(blank=True, null=True, upload_to='liked_playlist_covers/'),
        ),
    ]
