# Generated by Django 6.0.4 on 2026-05-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0005_playlist_liked_playlist_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='cover',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='liked_playlist_cover',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='liked_playlist_covers/'),
        ),
    ]
