# Generated by Django 6.0.4 on 2026-04-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='listenerprofile',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='listenerprofile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
