# Generated by Django 6.0.4 on 2026-04-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_artistprofile_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='listenerprofile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
