# Generated by Django 6.0.4 on 2026-04-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_artistprofile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listenerprofile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
