# Generated by Django 6.0.4 on 2026-04-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_nickname_alter_listenerprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
