# Generated by Django 6.0.4 on 2026-05-03 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_artistprofile_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listenerprofile',
            name='block_explicit',
        ),
    ]
