# Generated by Django 6.0.4 on 2026-05-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_playbacksession_cover_url_alter_playbacksession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
