# Generated by Django 6.0.4 on 2026-05-07 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_artistprofile_slug'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('music', '0010_album_is_explicit_song_is_explicit'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenerprofile',
            name='saved_albums',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='music.album'),
        ),
        migrations.CreateModel(
            name='RecentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
