# Generated by Django 6.0.4 on 2026-05-10 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_listenerprofile_saved_albums_recentitem'),
        ('music', '0010_album_is_explicit_song_is_explicit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistPlayCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_counts_by_users', to='accounts.artistprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_play_counts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-play_count', '-last_played'],
                'unique_together': {('user', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyArtistStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('month', models.CharField(max_length=7)),
                ('first_play_date', models.DateTimeField(auto_now_add=True)),
                ('last_play_date', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats_by_users', to='accounts.artistprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_artist_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_play_date'],
                'unique_together': {('user', 'artist', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MonthlySongStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('month', models.CharField(max_length=7)),
                ('first_play_date', models.DateTimeField(auto_now_add=True)),
                ('last_play_date', models.DateTimeField(auto_now=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats_by_users', to='music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_song_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_play_date'],
                'unique_together': {('user', 'song', 'month')},
            },
        ),
        migrations.CreateModel(
            name='SongPlayCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_counts_by_users', to='music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_play_counts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-play_count', '-last_played'],
                'unique_together': {('user', 'song')},
            },
        ),
    ]
