# Generated by Django 6.0.4 on 2026-05-11 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_artistplaycount_monthlyartiststats_monthlysongstats_and_more'),
        ('music', '0010_album_is_explicit_song_is_explicit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistplaycount',
            options={'verbose_name': 'Recuento de reproducciones de artista', 'verbose_name_plural': 'Recuentos de reproducciones de artistas'},
        ),
        migrations.AlterModelOptions(
            name='monthlyartiststats',
            options={'verbose_name': 'Estadística mensual de artista', 'verbose_name_plural': 'Estadísticas mensuales de artistas'},
        ),
        migrations.AlterModelOptions(
            name='monthlysongstats',
            options={'verbose_name': 'Estadística mensual de canción', 'verbose_name_plural': 'Estadísticas mensuales de canciones'},
        ),
        migrations.AlterModelOptions(
            name='songplaycount',
            options={'verbose_name': 'Recuento de reproducciones de canción', 'verbose_name_plural': 'Recuentos de reproducciones de canciones'},
        ),
        migrations.RenameField(
            model_name='monthlyartiststats',
            old_name='last_play_date',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='monthlysongstats',
            old_name='last_play_date',
            new_name='last_updated',
        ),
        migrations.RemoveField(
            model_name='monthlyartiststats',
            name='first_play_date',
        ),
        migrations.RemoveField(
            model_name='monthlysongstats',
            name='first_play_date',
        ),
        migrations.AlterField(
            model_name='artistplaycount',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_counts', to='accounts.artistprofile'),
        ),
        migrations.AlterField(
            model_name='monthlyartiststats',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to='accounts.artistprofile'),
        ),
        migrations.AlterField(
            model_name='monthlysongstats',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to='music.song'),
        ),
        migrations.AlterField(
            model_name='songplaycount',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_counts', to='music.song'),
        ),
    ]
