# Generated by Django 6.0.4 on 2026-05-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_artistplaycount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyartiststats',
            options={'ordering': ['-last_updated'], 'verbose_name': 'Estadística mensual de artista', 'verbose_name_plural': 'Estadísticas mensuales de artistas'},
        ),
        migrations.AlterModelOptions(
            name='monthlysongstats',
            options={'ordering': ['-last_updated'], 'verbose_name': 'Estadística mensual de canción', 'verbose_name_plural': 'Estadísticas mensuales de canciones'},
        ),
    ]
