# Generated by Django 6.0.4 on 2026-05-11 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_monthlyartiststats_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentitem',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
