# Generated by Django 6.0.4 on 2026-05-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_recentitem_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbacksession',
            name='session_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='playbacksession',
            unique_together={('user', 'session_id')},
        ),
    ]
