# Generated by Django 6.0.4 on 2026-05-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_fix_playback_session_unique_constraint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playbacksession',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='playbacksession',
            name='session_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
