# Generated by Django 6.0.4 on 2026-05-18 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_playbacksession_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='150 caracteres como máximo. Letras, dígitos, espacios y @/./+/-/_', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Introduzca un nombre de usuario válido. Este valor puede contener únicamente letras, números, espacios y los caracteres @/./+/-/_', regex='^[\\w\\s.@+-]+$')]),
        ),
    ]
