# Generated by Django 6.0.4 on 2026-05-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='banner',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='photo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='listenerprofile',
            name='avatar',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='profiles/'),
        ),
    ]
