# Generated by Django 6.0.4 on 2026-05-18 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_artistprofile_banner_alter_artistprofile_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='website',
        ),
    ]
