# Generated by Django 6.0.4 on 2026-05-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_artistprofile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbacksession',
            name='session_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='playbacksession',
            constraint=models.UniqueConstraint(fields=('user', 'session_id'), name='unique_user_session_id'),
        ),
    ]
