# Generated by Django 6.0.4 on 2026-05-19 17:39

from django.db import migrations


def copy_nickname_to_username(apps, schema_editor):
    """Copia nickname → username donde nickname no esté vacío y no haya colisión."""
    User = apps.get_model('accounts', 'User')
    for user in User.objects.exclude(nickname__isnull=True).exclude(nickname__exact=''):
        if not User.objects.filter(username=user.nickname).exclude(pk=user.pk).exists():
            user.username = user.nickname
            user.save(update_fields=['username'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_playbacksession_session_id_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_nickname_to_username, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
